### PR TITLE
Remove deprecated option in tests

### PR DESCRIPTION
**Pull request by RDIL**
Travis removed support `sudo: false` some time ago

### CODE REVIEW

**Comment by jleclanche** [comment]
Just remove the line please. And can you change the URL above to `https://travis-ci.org/jazzband/django-oauth-toolkit` while you're at it?

**Comment by RDIL** [comment]
Fixed

**Comment by jleclanche** [comment]
will merge once travis finishes

**Comment by RDIL** [comment]
👍

**Comment by jleclanche** [comment]
Any idea why it's failing? it looks like it's trying to run more envs than it should

**Comment by RDIL** [comment]
It’s been failing since the merge of #679

**Comment by jleclanche** [comment]
Something else is at play there because github is configured to prevent merges without travis passing. Any chance you can look at fixing travis?

**Comment by RDIL** [comment]
I can try, I’ll shoot the rodies an email also.

**Comment by RDIL** [comment]
Here’s a temp fix

**Comment by jleclanche** [comment]
Not ideal but I'll take it. Can move to this type of travis file: https://github.com/dj-stripe/dj-stripe/blob/master/.travis.yml

**Pull request merged**
