### PR TITLE
feat: containerized apps

### PR DESCRIPTION
**Pull request by dopry**
## Description of the Change

- add Dockerfile to build the tests/app/idp
- add Dockerfile to build the tests/app/rp
- add a docker compose file to build and start instances of the idp and rp

You can test this setup with
```docker-compose up```

This could be nice for testing new branches with the following

```
docker-compose down -v # remove existing env
docker-compose build      # rebuild the images
docker-compose up          # spin up the docker  compose environment
```

You should be able to goto http://localhost:5173 and http://localhost:8000 to access the compose instances. 

This is a precursor to publishing the test IDP as a container via docker hub. I hope making a Django based IDP more accessible will help grow our contributor and user community. 

## Checklist

- [X] PR only contains one change (considered splitting up PR)
- [N/A ] unit-test added
- [ ] documentation updated

   I wasn't quite sure where or how to document this at this juncture. I'm open to ideas.

- [N/A] `CHANGELOG.md` updated (only for user relevant changes)
- [X] author name in `AUTHORS`

### CODE REVIEW

**Comment by n2ygk** [comment]
@dopry this looks like a cool idea. Sorry for the delay in looking. Documentation could be short and simple -- "use docker-compose up to start up an OAuth server".

I had started doing something similar here https://github.com/n2ygk/dot-tutorial using Heroku and an attempt to try out some [OIDC certification testing](https://www.certification.openid.net/plan-detail.html?plan=23QYhdmrL1fkZ&public=true). See the [notes](https://github.com/n2ygk/dot-tutorial/blob/main/certification/notes.md)

There's a bunch of conflicts now -- maybe I merged something prematurely?

**Comment by dopry** [comment]
No worries. I'll update it when I get a chance.

**Comment by dopry** [comment]
@n2ygk This should be rebased and ready for a cursory review.

**Review by n2ygk — APPROVED** [review]
Looks good. I was able to fire up the docker container and did some minor testing (just a GET http://localhost:8000/o/.well-known/openid-configuration and a few of the links there)

Regarding future documentation, perhaps update https://django-oauth-toolkit.readthedocs.io/en/latest/tutorial/tutorial_01.html or add a new chapter to the tutorial?

**Pull request merged**
