### PR TITLE
Fixing issue #631 - returning the refresh token of previous token

### PR DESCRIPTION
**Pull request by ziXet**
adding the 'refresh_token' to the dictionary being returned when the refresh_token is being reused.

### CODE REVIEW

**Comment by jleclanche** [comment]
lgtm, can you add a test?

**Comment by jleclanche** [comment]
I'm not available to merge/release anything for the next couple of weeks. If you ping me in ~15 days about this I can take care of it.

**Comment by y-spreen** [comment]
I think this does not work as intended.

```
HTTP b'POST' request for ['<ip>', <port>]
Dispatching grant_type authorization_code request to <oauthlib.oauth2.rfc6749.grant_types.authorization_code.AuthorizationCodeGrant object at 0x7f3e98ad92b0>.
Token request validation ok for <oauthlib.Request url="/o/token/", http_method="POST", headers="{'REQUEST_METHOD': 'POST', 'QUERY_STRING': '', 'SCRIPT_NAME': '', 'PATH_INFO': '/o/token/', 'wsgi.multithread': True, 'wsgi.multiprocess': True, 'REMOTE_ADDR': '<ip>', 'REMOTE_HOST': '<ip>', 'REMOTE_PORT': 11512, 'SERVER_NAME': '<ip>', 'SERVER_PORT': '80', 'HTTP_HOST': '<host>', 'HTTP_ACCEPT': '*/*', 'HTTP_ACCEPT_ENCODING': 'deflate, gzip', 'CONTENT_TYPE': 'application/x-www-form-urlencoded', 'HTTP_REFERER': 'https://<host>/o/token/', 'HTTP_USER_AGENT': 'WordPress/4.9.8; <re>', 'HTTP_X_FORWARDED_HOST': '<host>', 'HTTP_X_REAL_IP': '<ip>', 'HTTP_X_FORWARDED_FOR': '<ip>, <ip>', 'HTTP_X_FORWARDED_PORT': '80', 'HTTP_X_FORWARDED_PROTO': 'http', 'CONTENT_LENGTH': '311', 'HTTP_CONNECTION': 'keep-alive'}", body="grant_type=authorization_code&code=<code>&client_id=<id>&client_secret=<sc>&redirect_uri=<re>">.
HTTP 200 response started for ['<ip>', <port>]
HTTP close for ['<ip>', <port>]
HTTP response complete for ['<ip>', <port>]
HTTP POST /o/token/ 200 [0.04, <ip>:<port>]
HTTP b'GET' request for ['<ip>', <port>]
Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x7f3e98c311a8>.
HTTP 200 response started for ['<ip>', <port>]
HTTP close for ['<ip>', <port>]<ip>
HTTP response complete for ['<ip>', <port>]
HTTP GET /api/user/ 200 [0.36, <ip>:<port>]
HTTP b'POST' request for ['<ip>', <port>]
Dispatching grant_type authorization_code request to <oauthlib.oauth2.rfc6749.grant_types.authorization_code.AuthorizationCodeGrant object at 0x7f3e98ad92b0>.
Client, '<id>' (<Application: WP Shop>), is not allowed access to scopes None.
Client error during validation of <oauthlib.Request url="/o/token/", http_method="POST", headers="{'REQUEST_METHOD': 'POST', 'QUERY_STRING': '', 'SCRIPT_NAME': '', 'PATH_INFO': '/o/token/', 'wsgi.multithread': True, 'wsgi.multiprocess': True, 'REMOTE_ADDR': '<ip>', 'REMOTE_HOST': '<ip>', 'REMOTE_PORT': 27054, 'SERVER_NAME': '<ip>', 'SERVER_PORT': '80', 'HTTP_HOST': '<host>', 'HTTP_ACCEPT': '*/*', 'HTTP_ACCEPT_ENCODING': 'deflate, gzip', 'CONTENT_TYPE': 'application/x-www-form-urlencoded', 'HTTP_REFERER': 'https://<host>/o/token/', 'HTTP_USER_AGENT': 'WordPress/4.9.8; <re>', 'HTTP_X_FORWARDED_HOST': '<host>', 'HTTP_X_REAL_IP': '<ip>', 'HTTP_X_FORWARDED_FOR': '<ip>, <ip>', 'HTTP_X_FORWARDED_PORT': '80', 'HTTP_X_FORWARDED_PROTO': 'http', 'CONTENT_LENGTH': '311', 'HTTP_CONNECTION': 'keep-alive'}", body="grant_type=authorization_code&code=<code>&client_id=<id>&client_secret=<sc>&redirect_uri=<re>">. InvalidGrantError('(invalid_grant)  <oauthlib.Request url="/o/token/", http_method="POST", headers="{\'REQUEST_METHOD\': \'POST\', \'QUERY_STRING\': \'\', \'SCRIPT_NAME\': \'\', \'PATH_INFO\': \'/o/token/\', \'wsgi.multithread\': True, \'wsgi.multiprocess\': True, \'REMOTE_ADDR\': \'<ip>\', \'REMOTE_HOST\': \'<ip>\', \'REMOTE_PORT\': 27054, \'SERVER_NAME\': \'<ip>\', \'SERVER_PORT\': \'80\', \'HTTP_HOST\': \'<host>\', \'HTTP_ACCEPT\': \'*/*\', \'HTTP_ACCEPT_ENCODING\': \'deflate, gzip\', \'CONTENT_TYPE\': \'application/x-www-form-urlencoded\', \'HTTP_REFERER\': \'https://<host>/o/token/\', \'HTTP_USER_AGENT\': \'WordPress/4.9.8; <re>\', \'HTTP_X_FORWARDED_HOST\': \'<host>\', \'HTTP_X_REAL_IP\': \'<ip>\', \'HTTP_X_FORWARDED_FOR\': \'<ip>, <ip>\', \'HTTP_X_FORWARDED_PORT\': \'80\', \'HTTP_X_FORWARDED_PROTO\': \'http\', \'CONTENT_LENGTH\': \'311\', \'HTTP_CONNECTION\': \'keep-alive\'}", body="grant_type=authorization_code&code=<code>&client_id=<id>&client_secret=<sc>&redirect_uri=<re>">').
Unauthorized: /o/token/
HTTP 401 response started for ['<ip>', <port>]
HTTP close for ['<ip>', <port>]
HTTP response complete for ['<ip>', <port>]
HTTP POST /o/token/ 401 [0.01, <ip>:<port>]
```

The exact same request is denied just one second afterwards.

**Comment by ziXet** [comment]
> I think this does not work as intended.
> 
> ```
> HTTP b'POST' request for ['<ip>', <port>]
> Dispatching grant_type authorization_code request to <oauthlib.oauth2.rfc6749.grant_types.authorization_code.AuthorizationCodeGrant object at 0x7f3e98ad92b0>.
> Token request validation ok for <oauthlib.Request url="/o/token/", http_method="POST", headers="{'REQUEST_METHOD': 'POST', 'QUERY_STRING': '', 'SCRIPT_NAME': '', 'PATH_INFO': '/o/token/', 'wsgi.multithread': True, 'wsgi.multiprocess': True, 'REMOTE_ADDR': '<ip>', 'REMOTE_HOST': '<ip>', 'REMOTE_PORT': 11512, 'SERVER_NAME': '<ip>', 'SERVER_PORT': '80', 'HTTP_HOST': '<host>', 'HTTP_ACCEPT': '*/*', 'HTTP_ACCEPT_ENCODING': 'deflate, gzip', 'CONTENT_TYPE': 'application/x-www-form-urlencoded', 'HTTP_REFERER': 'https://<host>/o/token/', 'HTTP_USER_AGENT': 'WordPress/4.9.8; <re>', 'HTTP_X_FORWARDED_HOST': '<host>', 'HTTP_X_REAL_IP': '<ip>', 'HTTP_X_FORWARDED_FOR': '<ip>, <ip>', 'HTTP_X_FORWARDED_PORT': '80', 'HTTP_X_FORWARDED_PROTO': 'http', 'CONTENT_LENGTH': '311', 'HTTP_CONNECTION': 'keep-alive'}", body="grant_type=authorization_code&code=<code>&client_id=<id>&client_secret=<sc>&redirect_uri=<re>">.
> HTTP 200 response started for ['<ip>', <port>]
> HTTP close for ['<ip>', <port>]
> HTTP response complete for ['<ip>', <port>]
> HTTP POST /o/token/ 200 [0.04, <ip>:<port>]
> HTTP b'GET' request for ['<ip>', <port>]
> Dispatching token_type Bearer request to <oauthlib.oauth2.rfc6749.tokens.BearerToken object at 0x7f3e98c311a8>.
> HTTP 200 response started for ['<ip>', <port>]
> HTTP close for ['<ip>', <port>]<ip>
> HTTP response complete for ['<ip>', <port>]
> HTTP GET /api/user/ 200 [0.36, <ip>:<port>]
> HTTP b'POST' request for ['<ip>', <port>]
> Dispatching grant_type authorization_code request to <oauthlib.oauth2.rfc6749.grant_types.authorization_code.AuthorizationCodeGrant object at 0x7f3e98ad92b0>.
> Client, '<id>' (<Application: WP Shop>), is not allowed access to scopes None.
> Client error during validation of <oauthlib.Request url="/o/token/", http_method="POST", headers="{'REQUEST_METHOD': 'POST', 'QUERY_STRING': '', 'SCRIPT_NAME': '', 'PATH_INFO': '/o/token/', 'wsgi.multithread': True, 'wsgi.multiprocess': True, 'REMOTE_ADDR': '<ip>', 'REMOTE_HOST': '<ip>', 'REMOTE_PORT': 27054, 'SERVER_NAME': '<ip>', 'SERVER_PORT': '80', 'HTTP_HOST': '<host>', 'HTTP_ACCEPT': '*/*', 'HTTP_ACCEPT_ENCODING': 'deflate, gzip', 'CONTENT_TYPE': 'application/x-www-form-urlencoded', 'HTTP_REFERER': 'https://<host>/o/token/', 'HTTP_USER_AGENT': 'WordPress/4.9.8; <re>', 'HTTP_X_FORWARDED_HOST': '<host>', 'HTTP_X_REAL_IP': '<ip>', 'HTTP_X_FORWARDED_FOR': '<ip>, <ip>', 'HTTP_X_FORWARDED_PORT': '80', 'HTTP_X_FORWARDED_PROTO': 'http', 'CONTENT_LENGTH': '311', 'HTTP_CONNECTION': 'keep-alive'}", body="grant_type=authorization_code&code=<code>&client_id=<id>&client_secret=<sc>&redirect_uri=<re>">. InvalidGrantError('(invalid_grant)  <oauthlib.Request url="/o/token/", http_method="POST", headers="{\'REQUEST_METHOD\': \'POST\', \'QUERY_STRING\': \'\', \'SCRIPT_NAME\': \'\', \'PATH_INFO\': \'/o/token/\', \'wsgi.multithread\': True, \'wsgi.multiprocess\': True, \'REMOTE_ADDR\': \'<ip>\', \'REMOTE_HOST\': \'<ip>\', \'REMOTE_PORT\': 27054, \'SERVER_NAME\': \'<ip>\', \'SERVER_PORT\': \'80\', \'HTTP_HOST\': \'<host>\', \'HTTP_ACCEPT\': \'*/*\', \'HTTP_ACCEPT_ENCODING\': \'deflate, gzip\', \'CONTENT_TYPE\': \'application/x-www-form-urlencoded\', \'HTTP_REFERER\': \'https://<host>/o/token/\', \'HTTP_USER_AGENT\': \'WordPress/4.9.8; <re>\', \'HTTP_X_FORWARDED_HOST\': \'<host>\', \'HTTP_X_REAL_IP\': \'<ip>\', \'HTTP_X_FORWARDED_FOR\': \'<ip>, <ip>\', \'HTTP_X_FORWARDED_PORT\': \'80\', \'HTTP_X_FORWARDED_PROTO\': \'http\', \'CONTENT_LENGTH\': \'311\', \'HTTP_CONNECTION\': \'keep-alive\'}", body="grant_type=authorization_code&code=<code>&client_id=<id>&client_secret=<sc>&redirect_uri=<re>">').
> Unauthorized: /o/token/
> HTTP 401 response started for ['<ip>', <port>]
> HTTP close for ['<ip>', <port>]
> HTTP response complete for ['<ip>', <port>]
> HTTP POST /o/token/ 401 [0.01, <ip>:<port>]
> ```
> The exact same request is denied just one second afterwards.

Can you please describe what you exactly did?

**Comment by y-spreen** [comment]
As I understand it, this fix should enable `REFRESH_TOKEN_GRACE_PERIOD_SECONDS` to give a token request a short window in which it can be repeated. The application I'm using is sending the same token request twice, but the second time it's denied with `InvalidGrantError('(invalid_grant) …`

Here is my settings:

```
OAUTH2_PROVIDER = {
    'REFRESH_TOKEN_GRACE_PERIOD_SECONDS': 15,
}
```

**Comment by y-spreen** [comment]
Upon further investigation, the request I'm having issues with is no refresh, but a general login token... Maybe I'll have to fix this another way.

**Comment by ziXet** [comment]
> Upon further investigation, the request I'm having issues with is no refresh, but a general login token... Maybe I'll have to fix this another way.

Yes. that's different.
In order to get a new token, you **must** use the refresh token.

**Comment by y-spreen** [comment]
I really don't get why this client is so broken. As a user, it just shows me `invalid_grant`. In the logs I can see that it's correctly logging in, fetching the user object, and _then it's accessing the token view again_, with the same auth code. So of course the login fails.

This only happens when the client does not recognize the user and has to create a user object in the local db. When I try again, after the error is shown, it works. No error the second time, no second token request. So strange

**Comment by ziXet** [comment]
Would you please merge this PR?
@jleclanche

**Pull request merged**
