### PR TITLE
fix(#638): concurrency issue on new token from refresh token

### PR DESCRIPTION
**Pull request by gbataille**
Seems to fix the many issues I have in production

The green step does the trick
refresh_token_logic_fixed

Code to generate the diagram [here](https://gist.github.com/gbataille/28573bf1ac4aca95e53351aa0056ff0a)

### CODE REVIEW

**Comment by MattBlack85** [comment]
can you write a test (with threads probably to simulate concurrency) that explains exactly where is the issue? I don't get very well why locking the row for a read guards against concurrency problems.

**Comment by gbataille** [comment]
writing test for concurrency is flaky at best.

What don't you understand?
after retrieving the refresh token, we are deriving things from it and/or
modifying it.
In a concurrent context, several process take decision/modify the
underlying database object without refreshing the RefreshToken instance in
memory. The lock is to prevent 2 concurrent process acting on the same
RefreshToken to enter together this part of the code

**Comment by jleclanche** [comment]
@gbataille Why the token lock instead of a db transaction?

**Comment by gbataille** [comment]
there is already a db transaction.
But a db transaction does not do anything if you don't take a lock. the
refreshtoken has already been put in memory. anything you do in django does
not care about the fact that the db is in a transaction. you are still not
operating on the "latest" data in a non-concurrent way

**Comment by jleclanche** [comment]
Yeah after reading more of the context I see what you mean. This is gtm and I don't think writing threaded tests for this is a particularly good idea either tbh.

**Comment by MattBlack85** [comment]
not objecting about tests, I made them when the case was really clear been successful with 0 problems.
select_for_update does not prevent other processes to access the resource, it doesn't allow other actors to write at the same time the same row afaik hence I don't get why you use the lock to get the actual value of the refresh token from the db

**Comment by gbataille** [comment]
select_for_update does a db lock while getting the record. If someone else
has a db lock on this object, it'll block until the lock is released.
this works because you are in a db transaction already.

In my graph, that means that everything below the green box where I take
the lock is sure to execute in a single thread fashion, which is what we
need since we take decisions/mutate state based on the refresh token record

**Comment by MattBlack85** [comment]
I used select_for_update often and I never noticed it blocking when fetching items from the DB, it does when you want to write the row which is locked tho. I also made a quick test where I wrote a small function acquiring a lock and sleeping. The 2nd actor is indeed able to fetch the same row  while the first hold the lock from the DB but it's not able to save it until the first actor relases the lock

**Comment by gbataille** [comment]
From the doc:

select_for_update(*nowait=False*, *skip_locked=False*, *of=()*)

Returns a queryset that will lock rows until the end of the transaction,
generating a SELECT ... FOR UPDATE SQL statement on supported databases.


But then it depends on your db and your db config (typically isolation
level of reads).

I have solved a lot of concurrency issues in my production with this trick.
That's what it's meant for. I use to do a dummy update of the record to
make sure it was locked, but select_for_update does just that.

I can guarantee that this strategy works (in a regular postgres setup at
least) in other cases. For this particular issue I investigated, I just put
my fork of the lib in production today, so I'll have more details in a
couple of days (the concurrency issue is reported about 10 times a day in
my production before fix)

**Comment by gbataille** [comment]
go damn man, I was just building up an example. I was about to publish some
lock traces :D you should have continued to disagree :D

Are you using sqlite locally? that might behave quite differently.

For "risk management" purpose, I did put this code in my production today,
which receives 100s of refresh token requests per days. So if you wait a
couple of days I can tell you
- whether the concurrency issue has disappeared (at least in my context)
- whether I saw some other undesirable effect come up

How does that sound?

**Comment by MattBlack85** [comment]
:D I am fully convinced of how your change is going to work and I'm sure it can fix the problem you are having :dancer: 
I can pretend further I disagree tho :bug: 
:+1:

**Comment by gbataille** [comment]
Sigh, so the situation seems slightly better in my production, but the issue did not disappear

image
The new code was put in prod where the cursor is. Histogram bars are issues per day. Seems to have halved (maybe) but definitely not stopped.

I'll try to spend a bit more time on it then

**Comment by gbataille** [comment]
I think we can get to the `get_original_scopes` thing without being in a transaction, and having taken the refresh token lock. I'm not 100 % sure yet of how django-oauth-toolkit and oauthlib are working together

This is the call stack when it fails
```
File "oauth2_provider/views/base.py", line 206, in post
    url, headers, body, status = self.create_token_response(request)
  File "oauth2_provider/views/mixins.py", line 125, in create_token_response
    return core.create_token_response(request)
  File "oauth2_provider/oauth2_backends.py", line 140, in create_token_response
    headers, extra_credentials)
  File "oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "oauthlib/oauth2/rfc6749/endpoints/token.py", line 117, in create_token_response
    request, self.default_token_type)
  File "oauthlib/oauth2/rfc6749/grant_types/refresh_token.py", line 59, in create_token_response
    self.validate_token_request(request)
  File "oauthlib/oauth2/rfc6749/grant_types/refresh_token.py", line 117, in validate_token_request
    request.refresh_token, request))
  File "oauth2_provider/oauth2_validators.py", line 616, in get_original_scopes
    return AccessToken.objects.get(source_refresh_token_id=rt.id).scope
```

Still digging

**Comment by MattBlack85** [comment]
what error is raising?

**Comment by gbataille** [comment]
Still the same `DoesNotExist: AccessToken matching query does not exist.` when trying to validate the refresh token (that has most likely been used a few milliseconds before)
I think this method in the stack is called
1. to validate the token
2. when creating the new token

And I guess I have fixed only 2 (if anything :) )

**Comment by cleder** [comment]
Fixing 1 thing is better than none. 
Should the scope of this PR be reduced to fix just the one thing?

**Comment by gbataille** [comment]
From my point of view yes. There is a different issue opened now for the
other thing

**Pull request merged**
