### PR TITLE
Remove stuff that was deprecated for 2.5.0

### PR DESCRIPTION
**Pull request by n2ygk**
## Description of the Change
Removes deprecations that were warned would be removed in 2.5.0

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [ ] documentation updated
- [x] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by n2ygk** [comment]
@dopry @tonial I took a crack at removing the deprecations you had added. Please take a look and make sure I didn't mess it up.

**Review by dopry — COMMENTED** [review]
Looks good at a glance. I'll give it a more thorough review tomorrow.

**Review by tonial — APPROVED** [review]
Seems good to me :+1:

**Review by dopry — APPROVED** [review]

**Comment by dopry** [comment]
Sorry work got the better for me for a hearbeat. LGTM.

**Pull request merged**
