### PR TITLE
Fix broken import in doc

### PR DESCRIPTION
**Pull request by CarlSchwan**
## Description of the Change

`inport os.environ` is incorrect since environ is not a module,  instead we just need to do `import os` and use `os.environ`

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [ ] unit-test added (not needed, no new code)
- [x] documentation updated
- [ ] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS` (not sure if this is needed, that change is not copyrightable because it's too trivial)

### CODE REVIEW

**Review by n2ygk — APPROVED** [review]
Thanks for this!

**Review by n2ygk — CHANGES_REQUESTED** [review]
@CarlSchwan Please do add yourself to AUTHORS anyway. It's not about copyright but about credit for contributing.

**Comment by n2ygk** [comment]
> @CarlSchwan Please do add yourself to AUTHORS anyway. It's not about copyright but about credit for contributing.

Never mind. I did it.

**Review by n2ygk — APPROVED** [review]

**Comment by CarlSchwan** [comment]
> > @CarlSchwan Please do add yourself to AUTHORS anyway. It's not about copyright but about credit for contributing.
> 
> Never mind. I did it.

Thanks!

**Pull request merged**
