### PR TITLE
Added management command to create applications

### LINKED ISSUE #689: Management command to create a Client Application
I am trying to use this library in my 1 API and 2 clients: 1 webclient and 1 android application.
I normally us automated CI/CD pipelines to deploy my scripts.

I am unable to easily auto-create the `Client Application` - https://django-oauth-toolkit.readthedocs.io/en/latest/tutorial/tutorial_01.html#create-an-oauth2-client-application

It would be awesome if there is a management command to do this so I can just run that and create 2 clients using a secret/key I create during my deployment process

### PR DESCRIPTION
**Pull request by MattBlack85**
fixes #689

### CODE REVIEW

**Comment by MattBlack85** [comment]
@auvipy maybe we can ask the guy who opened the issue?

**Comment by auvipy** [comment]
sure

**Comment by MattBlack85** [comment]
@AbdealiJK do you want to give this patch a go? It attempts to solve the issue you opened

**Comment by AbdealiJK** [comment]
This looks nice. Will give it a go in the weekend

**Comment by MattBlack85** [comment]
did anybody have a chance to test this?

**Pull request merged**
