### PR TITLE
prepare for 1.4.0 release

### PR DESCRIPTION
**Pull request by n2ygk**
## Description of the Change

1.4.0 Release

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [x] documentation updated
- [x] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by n2ygk** [comment]
@MattBlack85 Just need your merge of #920 and then final review here.

**Comment by MattBlack85** [comment]
@n2ygk push the date to the changelog and we are g2g :rocket:

**Comment by n2ygk** [comment]
> @n2ygk push the date to the changelog and we are g2g 🚀

@MattBlack85 ready for your review.

**Comment by n2ygk** [comment]
FYI I just noticed a bunch of merged PRs that were labeled for 1.5.0 milestone. I changed them to 1.4.0.

**Review by MattBlack85 — APPROVED** [review]
:rocket:

**Pull request merged**
