### PR TITLE
fix a bug in refresh token revocation

### PR DESCRIPTION
**Pull request by ryanpetrello**
fixes: https://github.com/jazzband/django-oauth-toolkit/issues/625

### CODE REVIEW

**Comment by ryanpetrello** [comment]
@synasius @jleclanche any thoughts on this PR?

**Comment by ryanpetrello** [comment]
Hey @jleclanche :)

What are the odds that this could get merged and released in the near future?  I work on an upstream open source project where we're currently maintaining our own fork of django-oauth-toolkit to deal with this:

https://github.com/ansible/awx/commit/87d6940158910c3e24c447f435851b344911d3fb

**Comment by jleclanche** [comment]
Thanks for the heads up. Merging and releasing 1.2.1.

**Comment by jleclanche** [comment]
Ok 1.2.1 will have to wait. But 1.1.3 is out and that should work for you @ryanpetrello. Cheers

**Pull request closed without merging**
