### PR TITLE
compat with LoginRequiredMiddleware middleware

### PR DESCRIPTION
**Pull request by dulmandakh**
## Description of the Change

Django 5.1 introduced `LoginRequiredMiddleware` to allow authentication across the site, and this PR adds compatibility with it using `login_not_required` decorator.

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [x] unit-test added
- [x] documentation updated
- [x] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by n2ygk** [comment]
please request a review when ready

**Comment by dulmandakh** [comment]
@n2ygk changed tests, but please don't pay attention to CI configuration changes. I'll rebase once https://github.com/jazzband/django-oauth-toolkit/pull/1455 merged.

**Comment by n2ygk** [comment]
> @n2ygk changed tests. Please don't pay attention to CI configuration changes, I'll rebase once #1455 merged.

OK #1455 merged to please rebase.

**Review by n2ygk — APPROVED** [review]
Thanks!

**Pull request merged**
