### PR TITLE
WIP: Workaround for MS SQL Server/pyodbc

### PR DESCRIPTION
**Pull request by n2ygk**
Workaround for this error (see #583): 
`pyodbc NotImplementedError: the backend doesn't support altering from/to AutoField.`
which is caused by the inability to AlterField from `AutoField` to `BigAutoField`

This alters the migrations (0001 & 0005) only when the default database engine is pyodbc.

I've tested with MS SQL Server and it seems to do the right thing. This may break migrations for anyone using this toolkit with MS SQL Server prior to migration 0005 of 2017-05-14 11:41 (commit c1cd5d7b575f12313f664036e52383ba5cabf0ec)

@jleclanche Please take a look as I'm not really sure this is the best approach, but hopefully it's one that will let projects to continue to use MS SQL Server without having to maintain separate migrations.

Also, I'm not sure checking `settings.DATABASES['default']['ENGINE']` is the right way to identify the database that the migration is using.

### CODE REVIEW

**Comment by jleclanche** [comment]
Shouldn't this be a bug filed against django or something?

Maybe we can reset the migrations at some point (like I did in dj-stripe) to prevent this from being an issue in the future, but for the time being, as all the migration does is alter the field size, maybe we can just recommend to --skip it for the very few mssql users out there.

Furthermore, the next version of Django will include migrations from Auto to BigAuto in the core itself so I suspect we will see a fix for this if there isn't one already.

I think I would rather reset the migrations than let this be an issue.

**Comment by n2ygk** [comment]
It's apparently a [limitation of mssql](https://github.com/michiya/django-pyodbc-azure/blob/549026d0f6b031f69ca27f0a488cfe2266677f10/sql_server/pyodbc/schema.py#L129-L133) so there will be breaking migrations for all django projects in the world that use mssql (not so many;-).

I agree that resetting the migrations would be way cleaner but wouldn't that also be a breaking change for anyone with existing models who has not yet updated to a newer release of DOT? I'm OK with that -- just something to document in release notes.

I've opened https://github.com/michiya/django-pyodbc-azure/issues/172  and referenced https://github.com/django/django/pull/8924

**Comment by jleclanche** [comment]
I've done migration reset releases twice in the past now. The pattern is:

- Release a major version with all the migrations
- Immediately after, release a new major version which resets all the migrations (and does nothing else).

**Comment by n2ygk** [comment]
Closing this PR as it only works around a single edge case (deficiency in MS SQL) that can be handled outside this project.

**Pull request closed without merging**
