### PR TITLE
Fix access token 500

### PR DESCRIPTION
**Pull request by discobeta**
Fixes https://github.com/jazzband/django-oauth-toolkit/issues/1318

## Description of the Change
We are now try / except when attempting to find a vali token to avoid a 500 `oauth2_provider.models.AccessToken.DoesNotExist: AccessToken matching query does not exist`

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [x] unit-test added
- [ ] documentation updated
- [x] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by dopry** [comment]
@discobeta could you review your tests? It looks like the new change isn't covered.

**Comment by discobeta** [comment]
added additional tests

**Comment by dopry** [comment]
@discobeta, It looks like https://github.com/jazzband/django-oauth-toolkit/pull/1337/checks?check_run_id=17910869256 still isn't covered. You probably need to setup a scenario where you make a valid AccessToken, delete the token, then make a request.

**Comment by discobeta** [comment]
Added a test for a deleted token

**Comment by dopry** [comment]
The except branch added by your patch is still not covered, https://app.codecov.io/gh/jazzband/django-oauth-toolkit/pull/1337?src=pr&el=h1&utm_medium=referral&utm_source=github&utm_content=checks&utm_campaign=pr+comments&utm_term=jazzband

**Comment by discobeta** [comment]
I pushed an update that covers this change. Can you please approve the
workflow to recheck coverage?

**Comment by discobeta** [comment]
@dopry It looks like this is now covered. Thank you for your recommendation and support with this.

https://app.codecov.io/gh/jazzband/django-oauth-toolkit/pull/1337?src=pr&el=tree&utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=jazzband#diff-b2F1dGgyX3Byb3ZpZGVyL29hdXRoMl92YWxpZGF0b3JzLnB5

**Comment by dopry** [comment]
I think the last thing we need is a changelog entry and adding yourself to Authors if you're not in there already.

**Comment by discobeta** [comment]
@dopry can you please take a look here and see if there are any further changes required?

**Review by dopry — APPROVED** [review]

**Pull request merged**
