### PR TITLE
remove MiddlewareMixin use

### PR DESCRIPTION
**Pull request by dulmandakh**
## Description of the Change

Remove MiddlewareMixin use, and convert to new style Django middleware.

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [x] unit-test added
- [ ] documentation updated
- [x] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

### CODE REVIEW

**Review by auvipy — CHANGES_REQUESTED** [review]
thanks for handling this. can you please check the build failures

**Comment by dulmandakh** [comment]
@auvipy tests are passing, had to remove python 3.6 and 3.7 from Django master environment because Django master supports only 3.8 and above.

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
can you cover this pr templates issues please  documentation updated
CHANGELOG.md updated (only for user relevant changes)
author name in AUTHORS

**Comment by dulmandakh** [comment]
@auvipy done

**Comment by auvipy** [comment]
a changelog entry in the 1.4.1 segment would be great https://github.com/jazzband/django-oauth-toolkit/blob/master/CHANGELOG.md

**Review by auvipy — APPROVED** [review]

**Pull request merged**
