### PR TITLE
1.4.1 release

### PR DESCRIPTION
**Pull request by n2ygk**
Fixes: #923 

## Description of the Change

A few minor changes. See [CHANGELOG.md](CHANGELOG.md)

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [ ] documentation updated
- [x] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by n2ygk** [comment]
@MattBlack85 I just realized that I don't think we saw a resolution to #923. I don't want to hold up 1.5.0 for it, so I think we're OK without it for now?

**Review by auvipy — APPROVED** [review]

**Comment by n2ygk** [comment]
> @MattBlack85 I just realized that I don't think we saw a resolution to #923. I don't want to hold up 1.5.0 for it, so I think we're OK without it for now?

Fixed this with b5e2cd5

**Comment by n2ygk** [comment]
Hmm, what's wrong with this picture? flake8 reports ` ./oauth2_provider/models.py:404:76: BLK100 Black would make changes.` here but doesn't complain when I run `tox -e flake8` locally. WTF?

**Review by MattBlack85 — APPROVED** [review]

**Comment by MattBlack85** [comment]
lgtm

**Pull request merged**
