### PR TITLE
Added documentation for using request token in Getting Started

### PR DESCRIPTION
**Pull request by doc-E-brown**
Added additional documentation for using the refresh token (issue #635 )

### CODE REVIEW

**Comment by doc-E-brown** [comment]
I'm not really sure why the code coverage decreased.  All upstream mods were included in the branch and the only changes were made to the documentation.

**Comment by cleder** [comment]
sometime the code coverage tools (not only coveralls) have unexpected outputs

**Comment by doc-E-brown** [comment]
Any update on getting this merged?

**Comment by auvipy** [comment]
thanks!!

**Pull request merged**
