### PR TITLE
Skip authentication for direct POST on endpoint

### PR DESCRIPTION
**Pull request by brat002**
## Description of the Change
The solution fixes a problem of automation when user should get an authorization code to send it to a client to exchange to token(hashikorp vault in example).
```
curl -k -vvv -sXPOST "http://127.0.0.1:8000/authorize/"  -d"grant_type=authorization_code&response_type=code&client_id=testvault&username=xxx&password=xxx&redirect_uri=http://127.0.0.1:8000&scope=openid profile&allow=1"
```
will look like
```
curl -k -vvv -sXPOST "http://127.0.0.1:8000/authorize/"  -d"grant_type=authorization_code&response_type=code&client_id=testvault&username=xxx&password=xxx&redirect_uri=http://127.0.0.1:8000&scope=openid profile"
```
as it should.

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [ ] documentation updated
- [ ] `CHANGELOG.md` updated (only for user relevant changes)
- [ ] author name in `AUTHORS`

### CODE REVIEW

**Review by n2ygk — CHANGES_REQUESTED** [review]
Can you please cite where in the OAuth 2.0 RFCs this added `allow` parameter is permitted?

**Comment by dopry** [comment]
@n2ygk allow is actually the result of the DOT AllowForm when authorization is requested this will have the value the user clicked.

**Review by dopry — CHANGES_REQUESTED** [review]
@brat002 thanks for creating this PR!  We need to tick two boxes before we can merge this.

1. Can you clarify your use case? While I know the allow is from our form, I want to be sure I understand the flow you're going for here. Wouldn't setting skip authorization on the application resolve this for you?  
2. We'll need tests for these changes before we can merge it.

**Comment by dopry** [comment]
@brat002 do you still have the time or inclination to finish working on this PR?

**Comment by n2ygk** [comment]
Closing as stale

**Pull request closed without merging**
