### PR TITLE
Issue 1185 add token to request

### LINKED ISSUE #1185: Accessing client/application from request
Debugging some OAuth-authenticated request, I noticed that it passes by this line:
https://github.com/jazzband/django-oauth-toolkit/blob/492a867499b50f348c28db4ef3e429e8f46dc412/oauth2_provider/oauth2_validators.py#L426

Although I can read `request.user` inside my "protected" views, the `client` attribute is not available.

I'd like to log some actions, registering the application the user authorized to make these actions.... Is it possible?

### PR DESCRIPTION
**Pull request by jhnbyrn**
Fixes #1185

## Description of the Change

Add the Token object to the request in the middleware. This makes it easy to access the Application object in views. 

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [x] unit-test added
- [x] documentation updated
- [x] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by n2ygk** [comment]
Please fill out the checklist in the PR description above and add the issue number after `Fixes #`.

It is important to document any new functionality and to write automated tests. See https://django-oauth-toolkit.readthedocs.io/en/latest/contributing.html

**Comment by jhnbyrn** [comment]
> Please fill out the checklist in the PR description above and add the issue number after `Fixes #`.
> 
> It is important to document any new functionality and to write automated tests. See https://django-oauth-toolkit.readthedocs.io/en/latest/contributing.html

Thanks for the feedback. I am not sure if this is considered relevant for the changelog - let me know.  I've done the other stuff.

**Comment by n2ygk** [comment]
> > Please fill out the checklist in the PR description above and add the issue number after `Fixes #`.
> > It is important to document any new functionality and to write automated tests. See https://django-oauth-toolkit.readthedocs.io/en/latest/contributing.html
> 
> Thanks for the feedback. I am not sure if this is considered relevant for the changelog - let me know. I've done the other stuff.

Yes please add to the changelog since you are adding functionality potentially used by some other user of the package.

**Review by n2ygk — APPROVED** [review]
Looks great @jhnbyrn. Thanks for this contribution.

**Pull request merged**
