### PR TITLE
Change remaining HttpResponse to JsonResponse

### LINKED ISSUE #987: Change JSON based HttpResponse to JSONResponse
https://github.com/jazzband/django-oauth-toolkit/blob/d90bb348f00886ae8321f8194f6275be9aa08f80/oauth2_provider/views/introspect.py#L48-L56

Any reason not to use `django.http.JSONResponse`?

### PR DESCRIPTION
**Pull request by Andrew-Chen-Wang**
Fixes #987 

## Description of the Change

Changes any valid `HttpResponse(json.dumps(), etc...` to `django.http.JsonResponse`

## Checklist

- [X] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [ ] documentation updated
- [ ] `CHANGELOG.md` updated (only for user relevant changes)
- [X] author name in `AUTHORS`

### CODE REVIEW

**Review by auvipy — COMMENTED** [review]
shouldn't the unit tests updated?

**Comment by Andrew-Chen-Wang** [comment]
@auvipy not sure what this means since I went straight from master and did not change models.py...:

```
flake8 run-test-pre: PYTHONHASHSEED='384501872'
24
  flake8 run-test: commands[0] | flake8 /home/runner/work/django-oauth-toolkit/django-oauth-toolkit
25
  [1929] /home/runner/work/django-oauth-toolkit/django-oauth-toolkit$ /home/runner/work/django-oauth-toolkit/django-oauth-toolkit/.tox/flake8/bin/flake8 .
26
  ./oauth2_provider/models.py:566:8: BLK100 Black would make changes.
27
  ERROR: InvocationError for command /home/runner/work/django-oauth-toolkit/django-oauth-toolkit/.tox/flake8/bin/flake8 . (exited with code 1)
```

**Comment by Andrew-Chen-Wang** [comment]
@auvipy we should pin flake8 in tox otherwise PRs could magically fail due to an unexpected upgrade:

https://github.com/jazzband/django-oauth-toolkit/blob/d90bb348f00886ae8321f8194f6275be9aa08f80/tox.ini#L75-L79

**Comment by auvipy** [comment]
isnt there any test for views?

**Comment by Andrew-Chen-Wang** [comment]
@auvipy what do you mean "aren't there any tests for views?" Seems like the normal test suite is running, just the style isn't right.

**Review by auvipy — APPROVED** [review]

**Review by auvipy — CHANGES_REQUESTED** [review]
changelog entry needed

**Comment by Andrew-Chen-Wang** [comment]
@auvipy updated

**Review by auvipy — APPROVED** [review]

**Comment by auvipy** [comment]
Required statuses must pass before merging

**Comment by Andrew-Chen-Wang** [comment]
finally found the linting problem. thanks for approving @auvipy !

**Pull request merged**
