### PR TITLE
1.6.1 release

### PR DESCRIPTION
**Pull request by n2ygk**
Fixes #

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [ ] documentation updated
- [x] `CHANGELOG.md` updated (only for user relevant changes)
- [x] author name in `AUTHORS`

### CODE REVIEW

**Comment by n2ygk** [comment]
@Andrew-Chen-Wang Let's just get 1.6.1 out there real quick and the we can work on #1055

**Review by Andrew-Chen-Wang — CHANGES_REQUESTED** [review]
The README's RST link in the explanation doesn't have an underscore after the ```. Also, not sure what packaging info changed? Was it the docs?

**Review by Andrew-Chen-Wang — APPROVED** [review]
I'll be gone for next few hours, so besides that one README comment, LGTM

**Comment by n2ygk** [comment]
> The README's RST link in the explanation doesn't have an underscore after the ```. Also, not sure what packaging info changed? Was it the docs?

Yeah, Getting RTFD back working and highlighting the warning about Django 4.0.0 probably not quite ready and a contributing update asking people to request a PR from `jazzband/django-oauth-toolkit`.

Please consider joining that team! See https://jazzband.co/projects/django-oauth-toolkit/join

```
django-oauth-toolkit$ git diff --name-only 1.6.0
.github/workflows/test.yml
.readthedocs.yml
CHANGELOG.md
README.rst
docs/contributing.rst
docs/requirements.txt
oauth2_provider/__init__.py
tox.ini
```

**Pull request merged**
