### PR TITLE
Drop retired Python 3.5

### PR DESCRIPTION
**Pull request by amureki**
## Description of the Change

Python 3.5 did reach end-of-life in September 2020:
https://www.python.org/downloads/release/python-3510/

We can safely remove it from CI to reduce test running time.

## Checklist

- [x] PR only contains one change (considered splitting up PR)
- [ ] unit-test added
- [x] documentation updated
- [x] `CHANGELOG.md` updated (only for user relevant changes)
- [ ] author name in `AUTHORS`

### CODE REVIEW

**Comment by amureki** [comment]
There is a funny artefact:
>build (3.5) Expected — Waiting for status to be reported

I don't think it is coming from code, but rather something was cached or so.

Also, I noticed that GH Actions are running twice, I took an opportunity to fix it in a separate PR: https://github.com/jazzband/django-oauth-toolkit/pull/937

**Review by n2ygk — APPROVED** [review]
Thanks!

**Comment by n2ygk** [comment]
@MattBlack85 @jezdez Do you know how we "unstick" this expected build (3.5)? This PR removes py35.

**Review by auvipy — APPROVED** [review]

**Comment by jezdez** [comment]
> @jezdez Do you know how we "unstick" this expected build (3.5)? This PR removes py35. I believe this has to be removed from the protect branch settings.

Yeah, no problem, I removed the branch protection for the 3.5 build.

**Pull request merged**
